name: PreRelease

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Generate version
      id: version
      run: |
        BUILD_NUMBER=${{ github.run_number }}
        VERSION="1.0.0-preview.$BUILD_NUMBER"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release
      
    - name: Pack NuGet package
      run: dotnet pack src/HttpFilesMW.Core/HttpFilesMW.Core.csproj --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} --output ./artifacts
      
    - name: Publish to NuGet (preview)
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
